### ISSUE TITLE
already mutably borrowed: BorrowError in logging

### ISSUE THREAD

**Issue by noskill** [trueagi-io/hyperon-experimental#241]
```
from hyperon import *

def test():
        program = '''
            (X Y)
            (Y Z)
            (Y W)
            (Z W)
            (!println (match &self (, ($x $y) ($y $z) ($y $w) ($z $w)) (add-atom &self ($y $x))))
        '''
        runner = MeTTa()
        result = runner.run(program)

        print(runner.space().get_atoms())

test()
```

stacktrace:

[log.txt](https://github.com/trueagi-io/hyperon-experimental/files/10673786/log.txt)

**Comment by luketpeterson** [comment]
The error in the stack trace is caused by a RefCell being duplicately borrowed - usually happens when an outer calling function holds a Ref and then an inner called function tries to re-borrow the RefCell.

This may already be resolved, or there may be more involved in reproducing it.  Running the test on current main produces expected output:
```
[GroundingSpace(addr=0x6000035cc0c8), (X Y), (Y Z), (Y W), (Z W), (!println (match GroundingSpace(addr=0x6000035cc018) (, ($x $y) ($y $z) ($y $w) ($z $w)) (add-atom GroundingSpace(addr=0x6000035cc018) ($y $x))))]
```

**Comment by luketpeterson** [comment]
Following up, I enabled logging and I notices a difference in the log from the crash case vs. my log:

From the panic trace:
```
[2023-02-07T09:59:26Z DEBUG hyperon::metta::runner] Metta::load_module_space: load module space stdlib
[2023-02-07T09:59:26Z DEBUG hyperon::space::grounding] IndexTree::add(): key: (: if (-> Bool Atom Atom $t)), value: 0
[2023-02-07T09:59:26Z DEBUG hyperon::space::grounding] IndexTree::add(): key: (= (if True $then $else) $then), value: 1
[2023-02-07T09:59:26Z DEBUG hyperon::space::grounding] IndexTree::add(): key: (= (if False $then $else) $else), value: 2
[2023-02-07T09:59:26Z DEBUG hyperon::space::grounding] IndexTree::add(): key: GroundingSpace(addr=0x5629c84e3d58), value: 0
[2023-02-07T09:59:26Z DEBUG hyperon::space::grounding] IndexTree::add(): key: (X Y), value: 1
[2023-02-07T09:59:26Z DEBUG hyperon::space::grounding] IndexTree::add(): key: (Y Z), value: 2
[2023-02-07T09:59:26Z DEBUG hyperon::space::grounding] IndexTree::add(): key: (Y W), value: 3
[2023-02-07T09:59:26Z DEBUG hyperon::space::grounding] IndexTree::add(): key: (Z W), value: 4
thread '<unnamed>' panicked at 'already mutably borrowed: BorrowError', /home/leron/projects/hyperon-experimental/lib/src/common/shared.rs:147:36
...
```

vs. from my run without an error:
```
[2023-03-07T02:53:05Z DEBUG hyperon::metta::runner] Metta::load_module_space: load module space stdlib
[GroundingSpace(addr=0x60000073c0c8), (X Y), (Y Z), (Y W), (Z W), (!println (match GroundingSpace(addr=0x60000073c018) (, ($x $y) ($y $z) ($y $w) ($z $w)) (add-atom GroundingSpace(addr=0x60000073c018) ($y $x))))]
```

I don't know if the lack of `IndexTree` logging is significant - ie. if a feature was disabled vs. fixed, or if it's totally irrelevant.

**Comment by noskill** [comment]
@luketpeterson 
difference in logs is due to me using (!println  instead of !(println!

But there was a lot of refactoring recently, particularly here https://github.com/trueagi-io/hyperon-experimental/commit/89f6456ba3f622276f4b22d8d73b99db09dadac4 i think the issue is fixed.

**Comment by vsbogd** [comment]
I am sorry for the confusion, the issue is not fixed actually, but I disabled the log statement which caused the issue.
The root cause is that `GroundingSpace` may include itself as a `Shared` grounded atom and it causes two issues:
- it is a loop link which cannot be released properly and leads to a memory leak
- this leads to the double borrowing while printing the instance of the `GroudningSpace`
